# test load

#g = LOAD "data/human.hg18.genome" AS GENOME;

a = LOAD "data/a.bed";
b = LOAD "data/b.bed";
c = LOAD "data/c.bed";
d = LOAD "data/bed3.bed";

l = LOAD "data/tiny*bed";

e = COUNT l;
PRINT e;


#e = MERGEMAX a,b,c,d WHERE SCORE(==100);
#e = FOREACH a,b,c,d WHERE SCORE(<100&>50&!=75),START(>1000),END(<10000),CHROM(=="chr1");
#e = FILTER a,b,c,d WHERE CHROM(=="chr1");
#PEAK e 10;
#e = FILTER a,b,c,d WHERE SCORE(<5);
#e = FOREACH a,b,c,d;
#e = FOREACH a,b,c,d WHERE SCORE(MIN);

#e = MERGEMAX a,b,c,d WHERE SCORE(SUM);
#COUNT e ;
#e = MERGEMIN a,b,c,d WHERE SCORE(SUM);
#COUNT e ;
#e = MERGEFLAT a,b,c,d WHERE SCORE(SUM);
#COUNT e ;

#PRINT e;

# test intersect
#e = INTERSECT a,b,c,d;

#e = a,b INTERSECT a,b,c,d;

#COUNT e;

#COUNT a;

#f = INTERSECT a,b;

#COUNT f;
#PRINT f;
#PRINT e;

#a_bed6 = CAST a AS BED6;

#d = MERGE a_bed6,b;
#d = MERGE a_bed6,b WHERE SCORE(MIN),DISTANCE(10);
#d = MERGE a_bed6,b;
#d = MERGE a_bed6 b;

#PRINT e;

#d = MERGE a,b,c WHERE SCORE(MIN);
#d = MERGE a,b,c WHERE DISTANCE(10);
#d = MERGE a,b,c WHERE DISTANCE(10),SCORE(MIN);
#d = MERGE a,b,c WHERE SCORE(MIN),SCORE(MIN);


#e = MERGEMIN d;				# assumes sccore is zero, d is BEDN
#e = MERGEMIN e SCORE(MIN);		# score is MIN of a,b,c
#e = MERGEMIN e SCORE(MAX);		# score is MAX of a,b,c
#e = MERGEMIN e SCORE(MAX a,b); # score is MIN of a,b
#e = MERGEMIN e SCORE(a*2);		# score is a * 2 
#SAVE e AS "merge-min_ab.bed"

#e = SUBTRACT a,b,c;

#PRINT d;
#SAVE d AS "intersect.bed";
#SAVE e AS "run.bed";
